/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
// https://generate.applyquick.ai
// platform
enum ENUM {
  ACCESS_TOKEN = '__SSHD_CAN',
  CHROME_ACCESS_TOKEN = 'blcfjlhmcfmnpgcklgkgnmgmjojjddoj',
  GOOGLE_CLIENT_ID = '/google-token-id',
  CLIENT_ID = '594177636197-b3v8b4umnp56kikek31bgaqs6jeajikd.apps.googleusercontent.com',
  // BASE_URL = "https://quick-apply-b4e936c5c50c.herokuapp.com/api/v1",
  BASE_URL = 'https://quick-apply-b4e936c5c50c.herokuapp.com/api/v1',
  GOOGLE_BASE_URL = 'https://quick-apply-dev-cf0a1835b9f4.herokuapp.com/api/v1',
  STRIPE_BASE_URL = 'https://quick-apply-b4e936c5c50c.herokuapp.com/stripe',
  SIGN_UP = '/users/signup',
  LOGIN_URL = '/users/login',
  // UPLOAD_FILE = '/documents',
  UPLOAD_FILE = '/users/files/uploads',
  GOOGLE_AUTH_URL = '/users/google-auth',
  START_PASSWORD_RESET = '/users/initiate-password-reset',
  PASSWORD_RESET = '/users/password-reset',
  GET_USER_DATA = '/users/data',
  GET_RESUME_COUNT = '/users/resumes/count',
  GET_APPLICATION_COUNT = '/users/job-applications/count',
  JOB_APPLICATION_PROFILE_UPDATE = '/users/job-applications/profile',
  JOB_APPLICATION_PROFILE_GET = '/users/job-applications/profile?platform=',
  UPDATE_USER_PROFILE = '/users/data',
  GET_ALL_RESUME = '/users/resumes',
  POST_RESUME_DATA = '/users/resumes',
  DELETE_RESUME = '/users/resumes/:',
  UPDATE_PASSWORD = '/users/passwords',
  DELETE_USER_PROFILE = '/users/data',
  LIST_JOB_APPLICATIONS = '/users/job-applications/details',
  SUBMIT_JOB_APPLICATIN_DETS = '/users/job-applications/details',
  CREATE_FEATURE_REQUEST = '/users/feature-requests',
  GET_USER_SUBSCRIPTION_PLAN = '/users/subscriptions',
  CANCEL_SUBSCRIPTION = '/users/subscriptions/cancellations',
  DELETE_MANY_RESUMES = '/users/resumes',
  DELETE_SINGLE_RESUME = '/users/resumes',
  DELETE_MANY_APPLICATIONS = '/users/job-applications/details',
  // stripe endpoints
  GET_STRIPE_PRICE = '/prices',
  STRIPE_CHECKOUT = '/create-checkout-session',
  CREATE_PORTAL_SESSION = '/create-portal-session',
  CREATE_USER_SUBSCRIPTION = '/users/subscriptions',
  CANCEL_USER_SUBSCRIPTION = '/users/subscriptions',
  GET_GOOGLE_SEARCH_RESULT = '/users/google-search',
  GET_GOOGLE_SEARCH_RESULT_AUTH = '/users/google-search/user',
}
export default ENUM;
